### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by dizlexik** [nosmokingbandit/QBittorrent-Chrome#1]
I actually found this about a week after you pushed it to GitHub but since it was so new I figured you hadn't yet gotten around to posting it to the Chrome Web Store and I didn't want to bug you about it. It's been a few weeks so I was wondering if you have any idea of when you might be posting it. This extension looks really great and it's exactly what I've been looking for :)

**Comment by nosmokingbandit** [comment]
I don't have a developer account and I don't want to spend the money to sign up since I've been out of work for a while. So for now loading it manually is the only option.

**Comment by dizlexik** [comment]
Ah, sorry to hear that, but I understand. I'll load it up manually. Thanks and keep up the great work!
